# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-
# stub: code_counter 0.3.1 ruby lib

Gem::Specification.new do |s|
  s.name = "code_counter"
  s.version = "0.3.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.require_paths = ["lib"]
  s.authors = ["Jon Frisby", "Dan Mayer"]
  s.date = "2014-06-06"
  s.description = "This is a port of the rails 'rake stats' method so it can be made more robust and work for non rails projects. New features may eventually be added as well."
  s.email = "jfrisby@mrjoy.com"
  s.executables = ["code_counter"]
  s.extra_rdoc_files = [
    "CHANGELOG.md",
    "LICENSE",
    "README.md"
  ]
  s.files = [
    "CHANGELOG.md",
    "LICENSE",
    "README.md",
    "bin/code_counter",
    "code_counter.gemspec",
    "lib/code_counter.rb",
    "lib/code_counter/engine.rb",
    "lib/code_counter/rake.rb",
    "lib/code_counter/version.rb"
  ]
  s.homepage = "http://github.com/MrJoy/code_counter"
  s.licenses = ["MIT"]
  s.required_ruby_version = Gem::Requirement.new(">= 1.9.2")
  s.rubygems_version = "2.2.2"
  s.summary = "Making a gem of the normal rails rake stats method, to make it more robust and work on non rails projects"
end

