$LOAD_PATH << File.dirname(__FILE__)
require File.join('code_counter', 'version')
require File.join('code_counter', 'fs_helpers')
require File.join('code_counter', 'reporter')
require File.join('code_counter', 'engine')
require File.join('code_counter', 'rake')
